app:
  ui1:
    host: 127.0.0.1
    port: 4200
    url: http://${app.ui1.host}:${app.ui1.port}
  auth-server:
    host: localhost
    port: ${server.port}
    url: http://${app.auth-server.host}:${app.auth-server.port}
    allowed-origins:
      - ${app.ui1.url}

spring:
  application:
    name: authorization-server
#  rabbitmq:
#    username: guest
#    password: guest
#    host: 127.0.0.1
#    port: 5672
#    virtual-host: /
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/projectdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  flyway:
    user: root
    password: password
    url: jdbc:mysql://localhost:3306/projectdb
    baseline-on-migrate: true
  jpa:
    properties:
      hibernate:
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true
          collationConnection: utf8_bin
    #database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      springframework:
        amqp: DEBUG
server:
  port: 8080